edited file main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,6 +50,23 @@ jobs:
           key: ${{ env.PRIVATE_SSH_KEY}}
           envs: PRIVATE_SSH_KEY,REGISTRY,REPOSITORY,IMAGE_TAG,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_REGION,PORT,DATABASE_URL
           script: |-
+            # Cài Docker nếu chưa có
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              sudo yum update -y
+              sudo yum install -y docker
+              sudo service docker start
+              sudo usermod -aG docker ec2-user
+            fi
+
+            # Cài AWS CLI nếu chưa có
+            if ! command -v aws &> /dev/null; then
+              echo "AWS CLI not found. Installing..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+            fi
+            
             # sudo apt update
             sudo service docker start
             sudo chmod 666 /var/run/docker.sock
